[profile.default]
src = "src"
solc = "0.8.24"
out = "out"
libs = ["lib"]
via_ir = true

remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "src/=src/"
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
